### ISSUE TITLE
Try to use but i don't found in plugin menu

### ISSUE THREAD

**Issue by virtualrobotix** [iamscottxu/obs-rtspserver#1]
Dear Sir,
i try to use your cool plugin.
I installed it but i don't found in plug in menu. Can you add some how to for getting starterd procedure.
thanks
Roberto

**Comment by dbl0null** [comment]
Hey,
got same situation
didn't have time to check for solution but it seems we got to satisfy some requirements by hand
libs needed:

![Снимок экрана 2020-07-30 в 11 10 44](https://user-images.githubusercontent.com/25458598/89063317-a0745d80-d370-11ea-8d22-9ebbaa83824b.png)

Qt5* libs
and vcruntime140 for visual studio2005

**Comment by iamscottxu** [comment]
You may need to install VC + + Runtime.
[https://cdn-fastly.obsproject.com/downloads/vc_redist.x64.exe](https://cdn-fastly.obsproject.com/downloads/vc_redist.x64.exe)

**Comment by tormyvancool** [comment]
It works greatly using VLC as receiver.

**Comment by RaziehSh1987** [comment]
thank you for your plugin, but It just send to  rtsp:// localhost server, how can I use to send to global RTSP server?

**Comment by gg22mm** [comment]
> thank you for your plugin, but It just send to rtsp:// localhost server, how can I use to send to global RTSP server?

这个问题这么明显，官方是看不见呢？还是不理解？ 我想知道一下，我很好奇~~

**Comment by RaziehSh1987** [comment]
Hi, I hope you are doing well.
I used this code to receive from RTSP:
[image: image.png]
[image: image.png]
[image: image.png]


And To send Unreal Engine level to RTSP:

Send Unreal Engine 5.1 Livestream to RTSP using Pixel streaming and Python

Show Unreal Engine 5.1  Level streaming in python:

I wrote code to:[“Show_level_Scene_unreal.py”]

To display the level scene of Unreal Engine 5 in Python using the OpenCV
library, we can use the Pixel Streaming plugin to stream the level to a web
browser, and then capture the frames from the browser and display them
using the cv2.imshow function. Here are the steps to do so:

   1.

   Install the Pixel Streaming plugin in your Unreal Engine 5 project and
   set up a Pixel Streaming server.
   2.

   Launch your project and start the Pixel Streaming session.
   3.

   Open a web browser and navigate to the Pixel Streaming URL to view the
   level scene.
   4.

   Install the selenium and webdriver-manager Python packages using pip:

Send Unreal Engine 5.1 Livestream to RTSP using Pixel streaming and Python:To
run:[Send_level_Scene_unrealEngine51_To_RTSP.py]

   -

   Run Pixel streaming server:
   -

      windows power shell>Rk>Run as an administrator>go to the above path
      by command(for cd unreal engine  → use cd “Unreal Projects”)>  run below
      command:
         Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
      -

      Then Cd “C:\Users\UnrealEngine_LMMV\Documents\Unreal
      Projects\CPlusPlus_prj\Samples\PixelStreaming\WebServers\SignallingWebServer\platform_scripts\cmd”
      -

         .\Start_SignallingServer.ps1
      -

      Open browser : http://10.10.100.179
      -

   Run RTSP server using docker:
   -

       Run Docker as an Adminisrator and Run below code in CMD as an
      Administrator:(RUN RTSP Server)
      -

      docker run --rm -it -e RTSP_PROTOCOLS=tcp -p 8554:8554 -p 1935:1935
      aler9/rtsp-simple-server
      -

   Run Unreal engine5.1 in Game mode > enable pixel streaming
   -

   Run Python code
   -

   Open VLC> media>Open Network Streaming> rtsp://localhost:8554/mystream
   >play

just I should use this FFmpeg setting

screenshot = driver.get_screenshot_as_png()


# read the PNG image data as a PIL Image object

img = Image.open(io.BytesIO(screenshot))



# get width and height

width, height = img.size


# set sizeStr

sizeStr = f"{width}x{height}"

print(sizeStr)

# sizeStr ="640x480"

fps = 30


# Set up the ffmpeg command

command = [

   "ffmpeg",

   "-re",

   "-s", sizeStr,

   "-framerate", str(fps),

   "-f", "rawvideo",

   "-pix_fmt", "bgr24",

   "-i", "pipe:",

   "-c:v", "libx264",

   "-preset", "veryfast",

   "-tune", "zerolatency",

   "-b:v", "2M",

   # "-g", "30",

   # "-bufsize", "64M",

   "-f", "rtsp",

   rtsp_server

]

and also I should change setting in VLC to show the output in fullscreen or
big size.
