### ISSUE TITLE
问题：设置成自动启动时，将不能推流！

### ISSUE THREAD

**Issue by iesvme** [iamscottxu/obs-rtspserver#10]
设置成自动启动时，将不能推流！

**Comment by iamscottxu** [comment]
我推测你指的是不能更改推流设置把，推流的话测试过是可以的。也就是说可以停止后再更改推流设置。
这个问题有可能是OBS本身的问题造成的，会进一步排查。

**Comment by iesvme** [comment]
不是的。如果先点启动，再推流，也是不行的。要先推流，才能启动；
同时样，甚至停止推流时，也要先停止插件，才能停止推流。

我的系统是：win10 LTSC X64

**Comment by iesvme** [comment]
测试了下，1.2.1版好像已经解决了！非常感谢！！！
