### ISSUE TITLE
macOS 12.4 / OBS 27.2.4 . RTSP 2.2.1

### ISSUE THREAD

**Issue by brusezot** [iamscottxu/obs-rtspserver#113]
Initialize encoder error, do you have a idea ?

**Comment by toruishihara** [comment]
With this change, worked on my environment on macOS12.5 Intel.

rtsp_output_helper.cpp
@@ -110,7 +110,7 @@ void RtspOutputHelper::CreateVideoEncoder()
        if (outputSettings.adv_out)
                encoder = obs_get_encoder_by_name("streaming_h264");
        else
-               encoder = obs_get_encoder_by_name("simple_h264_stream");
+               encoder = obs_get_encoder_by_name("simple_video_stream");
        obs_encoder_release(videoEncoder);
        videoEncoder = obs_video_encoder_create(
                obs_encoder_get_id(encoder), "rtsp_output_video",
