### ISSUE TITLE
How to decrease the latency?

### ISSUE THREAD

**Issue by xiaohaoxiang** [iamscottxu/obs-rtspserver#114]
There is always a latency of about 1.5s.
How to get the latency like Nvidia Shield+moonlight? Which is usually lower than 100ms.

**Comment by iamscottxu** [comment]
Please try to modify the player settings.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/22959917/193730309-16ae10af-2449-46b7-8b99-577aba174cfe.png">
