### ISSUE TITLE
是否计划支持obs 28.0 版本

### ISSUE THREAD

**Issue by yhuan416** [iamscottxu/obs-rtspserver#117]
目前插件不支持在obs 28版本上运行, 应该是qt版本更换导致的, 不知道作者是否有支持28版本的计划?

**Comment by iamscottxu** [comment]
Duplicate of #116.

**Comment by iamscottxu** [comment]
如果愿意，可尝试支持OBS 28的测试版插件([v3.0.0-beta1](https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.0.0-beta1))。
