### ISSUE TITLE
HEVC/x265 output not working

### ISSUE THREAD

**Issue by God-damnit-all** [iamscottxu/obs-rtspserver#124]
I'm on Windows 10 with OBS 28.0.0.2, using beta1 of the plugin. I have "NVIDIA NVENC HEVC" selected as the output and start streaming.

VLC 4 is able to pick up the audio but not the video. mpv won't play it period.

When I change to x264 or "NVIDIA NVENC H.264" it works correctly, leading me to believe that maybe HEVC/x265 isn't currently supported?

I'm well aware that HEVC/x265 videos aren't browser-compatible, but I would still like to stream to a friend using VLC. The HEVC codec would save a lot of network bandwidth.

**Comment by iamscottxu** [comment]
[v3.0.0-beta2](https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.0.0-beta2) added support for HEVC encoding.
