### ISSUE TITLE
V3.0.0-beta3 windows Nvidia nvenc broken

### ISSUE THREAD

**Issue by theofficialgman** [iamscottxu/obs-rtspserver#128]
There is no output in the rtsp stream when the Nvidia nvenc encoder is selected in the streaming settings. This worked perfectly in 27.X and the older versions of the plugin.

X264 does still work in this new version on obs 28

**Comment by andrecaleffi** [comment]
same problem here

**Comment by sophy228** [comment]
The issue is simple, the jim-nvenc get SPP header only after 1st encoded packet,  but rtsp output just ask encoder for SPP infomation before that, so rtso create H264 source with empty SPP, than  the rtsp client such as VLC report no SPP received ...

Hope author can fix such isse ..

**Comment by theofficialgman** [comment]
Can confirm fixed and available in the latest beta release https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.1.0-beta1
