### ISSUE TITLE
Plugin failed to load

### ISSUE THREAD

**Issue by iTzVirtual00** [iamscottxu/obs-rtspserver#134]
I get the `... failed to load` error after installing this plugin. I installed VC libraries as mentioned in https://github.com/iamscottxu/obs-rtspserver/issues/1#issuecomment-667784072,

![obs](https://user-images.githubusercontent.com/58611844/209455505-831c0932-94ee-4fe7-8e71-3d1ebe38b83b.png)

Log file:
[2022-12-25 03-26-53.txt](https://github.com/iamscottxu/obs-rtspserver/files/10299369/2022-12-25.03-26-53.txt)

Line 85: `Skipping module '../../obs-plugins/64bit/obs-rtspserver.dll' due to possible import conflicts`

**Comment by StarNumber12046** [comment]
I have this problem also

**Comment by c4artisan** [comment]
same

**Comment by makgit** [comment]
same

**Comment by MeansonChen** [comment]
The reason is the latest obs not support this plug.
I try the latest 27.2.4 version on 27.+.+ branch, it can be work.

**Comment by JonnyTech** [comment]
https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.0.0-beta3
