### ISSUE TITLE
Homebrew installed OBS and rtsp-server beta: plugin won't load

### ISSUE THREAD

**Issue by Archetrix** [iamscottxu/obs-rtspserver#137]
Hi i've got OBS installed via homebrew (macOS Ventura) and used the v3.0.0-beta3 installer package for obs-rtspserver.
OBS would not display the RTSP Server entry under tools. No issues or errors in logs and such.

Then i stumbled across a mention of a plugins-folder within the OBS.app/Contents/PlugIns/ and simply linked the obs-rtspserver plugin from /Library/Application\ Support/obs-studio/plugins/

`ln -s /Library/Application\ Support/obs-studio/plugins/obs-rtspserver.plugin /Applications/OBS.app/Contents/PlugIns/obs-rtspserver.plugin`

That did the trick for me. I'm not sure if some config file of the homebrew-built OBS does not include the Application Support folder. So this might be a homebrew issue but i thought best to post the solution here.

**Comment by Archetrix** [comment]
I'm updating here after an upgrade of OBS blew my solution because the link into the app folder got removed. 

After placing the plugin into ~/Library/Application\ Support/obs-studio/plugins/ i did not need to link it anymore and OBS found it automatically.

Looks like installing for all users does not work.

**Comment by iamscottxu** [comment]
Thanks!
