### ISSUE TITLE
Not compatible with OBS 29 

### ISSUE THREAD

**Issue by brusezot** [iamscottxu/obs-rtspserver#140]
Do you think if it possible to use with OBS 29 ?

![image](https://user-images.githubusercontent.com/60002613/225874176-ce8c2d9f-e4ee-4f27-aaa0-51eaf73c44e2.png)

**Comment by iamscottxu** [comment]
I need to know what type of video encoder you are using. This plugin does not support AV1. Please provide logs file if convenient.

**Comment by iamscottxu** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/22959917/225906047-7aa0326a-bb1b-441e-aed7-65005f831723.png">

**Comment by iamscottxu** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/22959917/225906848-f2c77f1f-3ec2-4e08-8fc5-e9379befbce6.png">

**Comment by brusezot** [comment]
My software use only QSV with rtsp / onvif

![image](https://user-images.githubusercontent.com/60002613/225909088-4ef3f5e9-9397-43d2-a40b-dfe8312c90cb.png)
