### ISSUE TITLE
Mac compatibility

### ISSUE THREAD

**Issue by rivera-ernesto** [iamscottxu/obs-rtspserver#15]
Is there a way, workaround, or intrinsic limitation that makes this particular plugin incompatible with Mac?

**Comment by brodi1** [comment]
Hi @rivera-ernesto, macos compatibility is still under development. https://github.com/iamscottxu/obs-rtspserver/tree/macos

Once it's finished/tested it should be available as a stable release.

**Comment by iamscottxu** [comment]
https://github.com/iamscottxu/obs-rtspserver/releases/tag/v1.3.0-rc7
