### ISSUE TITLE
Bug: 无法开始数据捕获(can't begin data capture)

### ISSUE THREAD

**Issue by Radium-bit** [iamscottxu/obs-rtspserver#154]
It cannot be work on OBS, and the prompt is "can't begin data capture". The error is as shown in the figure
RTSP服务器无法正常工作，它提示“无法开始数据捕获”。错误如图

**OS** : windows11 64bit
**OBS Ver** :  30.0.0
**Plugin Ver** : 3.0.0
**Platfrom** : x64

![](https://github.com/Radium-bit/res/blob/master/obserr.jpg?raw=true)

**Comment by wykananda** [comment]
Same error here on Intel Macbook Pro. 

OS : MacOS Intel Sonma
OBS Ver : 30.0.0
Plugin Ver : 3.0.0/3.1.0 beta

**Comment by csev1755** [comment]
This issues seems to be related to #155 and might be able to be resolved with a rollback to OBS 29.

**Comment by iamscottxu** [comment]
This bug has been fixed in the new beta version.
https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.1.0-beta2
