### ISSUE TITLE
Plug-in seemed to stop working in v30 OBS  :"Can't begin data capture"

### ISSUE THREAD

**Issue by fatmantech** [iamscottxu/obs-rtspserver#155]
Hello,

Opened OBS today and was hit with the update prompt. Let my version update from 29.0.2 to 30.0.0. This seemed to instantly break the RTSP server with all encoders, all settings. The dialog inside of the OBS RTSP server plug-in simply read "Can't begin data capture"

I tried different settings all around and never got a single result. Then I rolled back to v29, and worked on the first try. Then I tested hardware and software encoders at different resolutions. Everything works except high framerates; 1080i@29.97 works great for what I'm doing. I didn't try a bunch of different bit rates, I left it at 2500kbps.

Could be the result of my specific hardware setup, but I wanted to post this in hopes of saving others the time I took to troubleshoot.
Always try rolling OBS back first.

I hope you found this helpful.

**Comment by fatmantech** [comment]
I should have included system specs: Windows11 64bit, I5 6th gen, GeforceRTX 3060, 32GB Ram, Decklink Duo.

**Comment by csev1755** [comment]
Just confirming I had the same error on my Windows 11 machine. Rolled back to 29.1.3 and it works perfectly.

**Comment by iamscottxu** [comment]
This bug has been fixed in the new beta version.
https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.1.0-beta2

**Comment by goldsoft8888** [comment]
![image](https://github.com/iamscottxu/obs-rtspserver/assets/11472472/c7ea9bd8-d4af-45c9-837a-bd1e9c1638d1)

我发现，如果不选音轨，就会提示 “无法开始数据捕获” ，选择音轨后就正常了。  
OBS-Studio-30.0.2-Full-Installer-x64.exe  
obs-rtspserver-v3.1.0-beta2-windows-installer.exe

**Comment by iamscottxu** [comment]
> ![image](https://private-user-images.githubusercontent.com/11472472/292017259-bb96c474-b191-4422-982a-b5264e33024a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjMyMTgsIm5iZiI6MTcwMzI2MjkxOCwicGF0aCI6Ii8xMTQ3MjQ3Mi8yOTIwMTcyNTktYmI5NmM0NzQtYjE5MS00NDIyLTk4MmEtYjUyNjRlMzMwMjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE2MzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMzMyZjdlOWE1OGY5YjhmNDRhZjBmNTlkNTE4NzE5NDJlNjU2ODBkZmQ2MzMyYTgxOGU1ZGU0YWI2MzUzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MNFgYU17DKe_qRb0lfTGq_hD2kKJRMoPyvqMOwnx5x8)
> 
> 我发现，如果不选音轨，就会提示 “无法开始数据捕获” ，选择音轨后就正常了。 OBS-Studio-30.0.2-Full-Installer-x64.exe obs-rtspserver-v3.1.0-beta2-windows-installer.exe

https://github.com/iamscottxu/obs-rtspserver/releases/tag/v3.1.0-beta3
