### ISSUE TITLE
后续是否能支持html，http地址查看？

### ISSUE THREAD

**Issue by iesvme** [iamscottxu/obs-rtspserver#17]
如果能在网页直接打开观看，就无敌了！

**Comment by brodi1** [comment]
您好 @iesvme 也许你有兴趣: https://github.com/Streamedian/html5_rtsp_player

**Comment by iesvme** [comment]
好的，谢谢。

**Comment by iamscottxu** [comment]
如果想直接在网页上播放，RTSP是不行的，透过websocket传输是一种方法。

**Comment by iesvme** [comment]
谢谢这么详细地回复。实在不行那就算了， rtsp本身就挺好的。
