### ISSUE TITLE
OBS studio crashing when starting the server

### ISSUE THREAD

**Issue by jeremyVignelles** [iamscottxu/obs-rtspserver#54]
I'm trying to use this plugin, but OBS crashes when I click "Start".

Here is the crash dump:
[crash.txt](https://github.com/iamscottxu/obs-rtspserver/files/6336039/crash.txt)

Does that mean something to you ?

OS : Windows 10 x64
OBS Studio 26.1.1 (64 bits)
1 scene with only my webcam in fullscreen.

**Comment by brodi1** [comment]
Hi @jeremyVignelles! Do you have hardware encoding (e.g. NVENC) enabled?

**Comment by jeremyVignelles** [comment]
I do, and changing to use QSV indeed works better. Is that a known bug ?

**Comment by brodi1** [comment]
Yeah I think.... Issue #48 has a similar problem.... but on linux. I myself have also experienced the same problem (on linux) with my nvidia gpu.

Adding nvidia support will not be that easy, I think. That could take a while. 
Unfortunately, I don't have a quick temporary solution ready at the moment.

**Comment by jeremyVignelles** [comment]
Closing in favor of #55 then
