### ISSUE TITLE
Support for NVENC

### ISSUE THREAD

**Issue by brodi1** [iamscottxu/obs-rtspserver#55]
If you activate NVENC and start the rtsp-server, OBS crashes.
This problem has already been seen with Windows and Linux.

I tried it myself multiple times with my NVIDIA GPU on Linux, but strangely enough it only crashes after about 20-25 seconds after starting the rtsp-server.

See issue: #48 and #54

**Comment by jeremyVignelles** [comment]
It crashes immediately on my side on windows.

**Comment by iamscottxu** [comment]
I used the NVENC encoder to test and failed to reproduce the error. Can you provide more detailed configuration information?

**Comment by iamscottxu** [comment]
I used the NVENC encoder to test and failed to reproduce the error. Can you provide more detailed configuration information?

**Comment by iamscottxu** [comment]
Using NVENC and enabled output scaling may cause the program to crash, please try to disable output scaling.
