### ISSUE TITLE
Output immediately paused?

### ISSUE THREAD

**Issue by hailwood** [iamscottxu/obs-rtspserver#59]
As soon as I start the RTSP-Server the output appears to get paused - 

Obs-studio 27.0.0-rc5 & rc6
Ubuntu 21.04

```
14:27:54.990: [NVENC encoder: 'rtsp_output_video'] settings:
14:27:54.990: 	rate_control: CBR
14:27:54.990: 	bitrate:      10000
14:27:54.990: 	cqp:          0
14:27:54.990: 	keyint:       250
14:27:54.990: 	preset:       hq
14:27:54.990: 	profile:      high
14:27:54.990: 	width:        1920
14:27:54.990: 	height:       1080
14:27:54.990: 	2-pass:       false
14:27:54.990: 	b-frames:     2
14:27:54.990: 	psycho-aq:    1
14:27:54.990: 	GPU:          0
14:27:54.990: 
14:27:55.087: libfdk_aac encoder created
14:27:55.087: libfdk_aac bitrate: 160, channels: 2
14:27:55.088: starting rtsp frame push thread
14:27:55.088: starting rstp server on port '8554'
14:27:55.275: output RTSP Output paused
```

**Comment by brodi1** [comment]
Hi @hailwood! Is at least one client connected? If so does the streaming work?

I have tested it with OBS 27.0.0 and as soon as a client is connected the RTSP output is immediately unpaused. It works for me .....

**Comment by hailwood** [comment]
Hi @brodi1,

I tried connecting with VLC and it just hangs indefinitely and nothing changes in the output
![image](https://user-images.githubusercontent.com/709773/121823312-934a2e00-ccf8-11eb-90b0-cc05bb1aebe3.png)

Of note, *something* is happening because as soon as I stop the RTSP server VLC shows
![image](https://user-images.githubusercontent.com/709773/121823338-b96fce00-ccf8-11eb-8f3d-fd7ed56b6937.png)

I've tried different ports etc

Don't know if it matters, but these are my stream output settings
![image](https://user-images.githubusercontent.com/709773/121823358-d906f680-ccf8-11eb-9c36-95430b86ae46.png)
