### ISSUE TITLE
Bitrate doesn't exceed 2800 kbps

### ISSUE THREAD

**Issue by dam034** [iamscottxu/obs-rtspserver#75]
Hi,
I'm trying to stream a 1080p video source received by a hdmi input.
The quality of the source is excellent and fluid, like the television signal.
In OBS I can see the source to the quality I just wrote.
In settings panel, I put 30000kbps stream, but when I connect a client to see the stream, it doesn't exceed 2800kbps, causing you to lose a lot of video quality.
I'm trying to stream in LAN, where the speed is 1gbps. While streaming, the CPU usage is about 10% and GPU usage about 30%.

I want to increase the bitrate from 2800kbps to 20000-30000kbps to have the source quality also on lan clients.

**Comment by brodi1** [comment]
Hi @dam034 

Could you please provide more information?
Such as:

- Operating system
- OBS version
- obs-rtspserver version
- is hardware encoding enabled?
- is vaapi enabled? (if you use linux)
- which software do you use to receive the stream?

**Comment by dam034** [comment]
Hi, sorry for the delay.

So I have:

- Windows 10 1903
- OBS 26.1.1 64bit
- obs-rtspserver version 2.0.7
- software encoding x264 (in that pc there is a GT 1030, but NVENC isn't available)
- ...
- vlc or obs on another pc in same lan at 1gbps

If necessary, I can make images/videos of any kind.

**Comment by brodi1** [comment]
Hi, @dam034 

Thanks. Could you make a screenshot of your settings?

I myself often have problems with VLC .... Maybe there's a bug that needs to be fixed?. 
Try [SMPlayer](https://www.smplayer.info/) or [mpv](https://mpv.io/) both work for me

If you try out [SMPlayer](https://www.smplayer.info/) you can press CTRL + I to see the information, you should also see the bitrate.

**Comment by dam034** [comment]
Now I've taken screenshots of OBS:

![obs1](https://user-images.githubusercontent.com/87028345/126234975-cea0e363-78a1-4419-a994-89355853fdf0.png)
![obs2](https://user-images.githubusercontent.com/87028345/126234982-4ec558bb-9d83-4245-82b5-02e4b5f29f56.png)

I used VLC, OBS (to see the stream) and vMix to receive the stream from the server, and despite the settings, the bitrate remains within 2800kbps.

I'm willing to do more tests if needed to understand what the problem is.

**Comment by brodi1** [comment]
I usually always use the Advanced (Avanzate) option .... now I've selected your settings and now I don't get more than 2800kbps.

Have you already tried whether the advanced option makes a difference?

Don't forget to:
- select CBR
- disable Rescale Output (Riscala l'uscita)

It works for me when I switch to the advanced option

**Comment by dam034** [comment]
Sorry, but I can't understand what you want to tell.

So I show the advanced and video settings in obs:
![obs3](https://user-images.githubusercontent.com/87028345/126673320-6012da11-9238-415c-b0ee-497e91374f78.png)
![obs4](https://user-images.githubusercontent.com/87028345/126673329-aef0abbe-778d-4a24-a46a-bb20cb816034.png)

If I was wrong somewhere, could you tell me the error?

If it's possible, can you show your right settings?

**Comment by brodi1** [comment]
@dam034 
![grafik](https://user-images.githubusercontent.com/69462234/126862590-9d453e39-f894-42d1-aa6e-f6bf9c25f269.png)

**Comment by dam034** [comment]
Sorry for the delay.

So I tried with your settings and these settings:
![obs rtsp](https://user-images.githubusercontent.com/87028345/127575876-38f90544-f1cb-4054-89ec-a9a088da87d0.png)

And when I'm viewing the stream on a pc in the same lan, I can encounter some systematic problems:
- on VLC, the quality is the maximum, as if I'm on the rtsp server to see the video, but sometimes the video freezes for 2-3 seconds, but the audio continues to flow;
- on OBS, the quality is the maximum as VLC, but sometimes the video lags for the same time as VLC but scrolls seeing bad (such as low bitrate).

With my settings, the bitrate can reach 70mbps, so no problem for my lan, which has 1gbps speed.

Now I want to know if the problem is on the server or on the clients.




p.s.: I have another problem of another type with this plugin, can I open another issue or continue here?

**Comment by brodi1** [comment]
@dam034

 you selected CRF.... have you tried CRB?

Here some info about encoding methods:

 **Summaries the strengths and weaknesses of the four encoding methods**
<figure class="wp-block-table"><table><tbody><tr><td><strong>Technique</strong><strong></strong></td><td><strong>Operation</strong></td><td><strong>Strengths</strong></td><td><strong>Weaknesses</strong></td><td><strong>Use for</strong></td></tr><tr><td>CBR</td><td>– Adjusts quality to achieve bitrate<br>– Same bitrate entire file</td><td>– Consistent bitrate <br>– Single pass</td><td>– Overall quality<br>– Transient quality</td><td>– Live <br>– VOD with constrained bandwidth</td></tr><tr><td>Constrained VBR</td><td>– Adjusts quality to achieve bitrate<br>– Adjusts bitrate to scene complexity</td><td>– Overall quality <br>– Transient quality</td><td>– Bitrate variability<br>– Cost (2 or more passes)</td><td>– Most other VOD</td></tr><tr><td>CRF</td><td>– Adjusts data rate to achieve quality</td><td>– Single pass<br>– Delivers set quality level</td><td>– No bitrate control</td><td>– Archiving<br>– Mezz file creation</td></tr><tr><td>Capped CRF</td><td>– CRF with data rate maximum</td><td>– Per-title method<br>– Single pass</td><td>– Transient quality<br>– Bitrate variability</td><td>– VOD<br>– Live</td></tr></tbody></table></figure>
Source: https://ottverse.com/what-is-cbr-vbr-crf-capped-crf-rate-control-explained/

> p.s.: I have another problem of another type with this plugin, can I open another issue or continue here?
A: You can open a new issue

**Comment by dam034** [comment]
So I tried 2 methods, CBR and CRF:
![rtsp1](https://user-images.githubusercontent.com/87028345/128181109-a92f6314-1457-4618-8eac-721913e19496.png)
![rtsp2](https://user-images.githubusercontent.com/87028345/128181114-8a9256c2-c3ac-4c8c-866a-2d0c80bf1fbc.png)

The OBS server is on Win 10 Pro platform, with GPU encoding unavailable.

I tried some tests with another pc in the same lan at 1 gbps speed, and it doesn't have the GPU encoding either:
1) VLC on Win 10, CBR method, it works without problems;
2) VLC on Ubuntu 18.04, CBR method, it works without problems;
3) OBS on Ubuntu 18.04, CBR method, very low quality, you can see the big squares;
4) VLC on Win 10, CRF method, it looks good, but when the bitrate slows down, the image freezes until the bitrate returns to high;
5) VLC on  Ubuntu 18.04, CRF method, it looks good, but when the bitrate slows down, the image freezes until the bitrate returns to high;
6) OBS on Ubuntu 18.04, CRF method, very low quality, you can see the big squares and it freezes when bitrate slows down.

I am very satisfied with tests #1 and #2, although at the beginning of the connection, the image does not come immediately. As I press Start, the audio arrives after not even a second, but to get the image I have to wait 10 seconds, but for me this fact is not a problem. These are VLC settings when I open the stream:
![vlc](https://user-images.githubusercontent.com/87028345/128183354-4757faac-d2d1-459d-ab63-2d0a35084a72.png)

Now I created this RTSP server to send the stream to a pc where there is a software streaming which will receive the data. But OBS (client) doesn't receive the signal well.

What do you advise?

**Comment by dam034** [comment]
Yes, you can close this issue.

I'm opening another issue, as requested in previous post.
