### ISSUE TITLE
RTSP always binds to localhost

### ISSUE THREAD

**Issue by Traace** [iamscottxu/obs-rtspserver#81]
RTSP always binds to localhost, i've found no way to change the adapter / address.

on windows localhost is handled by "Microsoft Loopback-Adapter", by default this adapter does not map to other adapters. Meaning applications that only listen on localhost are isolated from the LAN.
Therefore no applications beside the local system where RTSP Server runs can access the stream. Making this project pointless in my opinion.

Please make it possible to change IP...

**Comment by OGD09** [comment]
+1

**Comment by gg22mm** [comment]
> Although it is displayed as "localhost", it is actually bound to all ip addresses. If other devices cannot connect, please check the firewall settings of the operating system.

如何绑定到 远程服务器上（如阿里云服务器: www.baidu.com） 的地址？ 而非本地。
