### ISSUE TITLE
Linux Install QT Dependency

### ISSUE THREAD

**Issue by tlivesay** [iamscottxu/obs-rtspserver#94]
Attempting to run the plugin on Ubuntu 18.04 resulted in an error in the OBS log:
os_dlopen(/home/hti/.config/obs-studio/plugins/obs-rtspserver/bin/64bit/obs-rtspserver.so->/home/hti/.config/obs-studio/plugins/obs-rtspserver/bin/64bit/obs-rtspserver.so): /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /home/hti/.config/obs-studio/plugins/obs-rtspserver/bin/64bit/obs-rtspserver.so)
Module '/home/hti/.config/obs-studio/plugins/obs-rtspserver/bin/64bit/obs-rtspserver.so' not loaded

Ubuntu 18 isn't going past QT 5.9.5 at the moment, https://packages.ubuntu.com/search?keywords=qtbase-opensource-src+&searchon=sourcenames

This should either be made backwards compatible to work with Ubuntu 18 out of the box, or directions added to update QT to 5.12.
The latest .run can be downloaded at https://download.qt.io/official_releases/qt/5.12/

**Comment by iamscottxu** [comment]
Thanks for the Feedback.
