### ISSUE TITLE
Installer infected with malware?

### ISSUE THREAD

**Issue by iticory** [iamscottxu/obs-rtspserver#95]
Microsoft believes the current version of your windows installer is infected with a trojan

https://www.virustotal.com/gui/file/9d61a3a9d1172dece029f82d03ddec7bcbf2a432f178c49ea3db1166b2e7e2a5

![image](https://user-images.githubusercontent.com/1079448/139347740-bacb5340-543a-4dc3-8c58-1091ced5b2ec.png)

**Comment by iamscottxu** [comment]
The problem that was incorrectly identified as malware by the antivirus program has been restored.
![image](https://user-images.githubusercontent.com/22959917/140596751-eeab4e74-caf5-4647-b700-83a8fedeffdc.png)
